CREATE DATABASE IF NOT EXISTS Lab1Ciber;
USE Lab1Ciber;

DROP TABLE IF EXISTS `USERS`;
DROP TABLE IF EXISTS `PRODUCTS`;


CREATE TABLE IF NOT EXISTS `USERS` (
    idUser INT AUTO_INCREMENT PRIMARY KEY,
    correo VARCHAR(100) NOT NULL,
    contrasen VARCHAR(230) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUCTS` (
    idProduct INT AUTO_INCREMENT PRIMARY KEY,
    imagenProduct VARCHAR(255) NOT NULL,
    nameProduct VARCHAR(50) NOT NULL,
    descrip TEXT NOT NULL,
    price DECIMAL(20,4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;