CREATE DATABASE IF NOT EXISTS Lab1Ciber;
USE Lab1Ciber;

CREATE TABLE IF NOT EXISTS `USERS` (
    idUser INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(25) NOT NULL UNIQUE,
    contrasen VARCHAR(230) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `PRODUCTS` (
    idProduct INT AUTO_INCREMENT PRIMARY KEY,
    imagenProduct VARCHAR(255) NOT NULL,
    nameProduct VARCHAR(50) NOT NULL,
    descrip TEXT NOT NULL,
    price DECIMAL(20,4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;